name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest  # You can change this to your preferred OS (ubuntu-latest, macos-latest, etc.)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures a full clone for better analysis relevancy
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Add your SONAR_TOKEN as a secret in GitHub
